### ISSUE TITLE
Format generated code

### ISSUE THREAD

**Issue by roman01la** [roman01la/html-to-react-components#1]
The output code currently goes straight from Babylon generator and AST doesn't include code formatting information. Since generated code is intended to be used later by developers, it should be formatted according to some preferences. This will free developers from formatting every module by hand.

The sample output currently is the following:

ES5 React component as ES6 module
```js
import React from "react";
import Heading from "./heading";
import Nav from "./nav";
const Header = React.createClass({
  render() {
    return <header className="header">
        <Heading></Heading>
        <Nav></Nav>
      </header>;
  }

});
export default Header;
```

ES5 React component as CommonJS module
```js
const React = require("react");

const Heading = require("./heading");

const Nav = require("./nav");

const Header = React.createClass({
  render() {
    return <header className="header">
        <Heading></Heading>
        <Nav></Nav>
      </header>;
  }

});
module.exports = Header;
```

ES6 React component as ES6 module
```js
import React from "react";
import Heading from "./heading";
import Nav from "./nav";

class Header extends React.Component {
  render() {
    return <header className="header">
        <Heading></Heading>
        <Nav></Nav>
      </header>;
  }

}

export default Header;
```

ES6 React component as CommonJS module
```js
const React = require("react");

const Heading = require("./heading");

const Nav = require("./nav");

class Header extends React.Component {
  render() {
    return <header className="header">
        <Heading></Heading>
        <Nav></Nav>
      </header>;
  }

}

module.exports = Header;
```

Stateless React component as ES6 module
```js
import React from "react";
import Heading from "./heading";
import Nav from "./nav";

const Header = () => <header className="header">
        <Heading></Heading>
        <Nav></Nav>
      </header>;

export default Header;
```

Stateless React component as CommonJS module
```js
const React = require("react");

const Heading = require("./heading");

const Nav = require("./nav");

const Header = () => <header className="header">
        <Heading></Heading>
        <Nav></Nav>
      </header>;

module.exports = Header;
```

The code should be formatted using [CST](https://github.com/cst/cst). This format supports whitespace, punctuators and comments.

## TODO

- [x] Insert new line character between import/require declarations block and component's variable declaration in ES5 React components as ES6 modules.
- [x] Insert new line character between component's variable declaration and export declaration in ES5 React components as ES6 and CommonJS modules.
- [x] Remove new line characters between imported module variable declarations in CommonJS modules.
- [x] Wrap JSX into parens if root JSX element doesn't have child JSX elements and move JSX on a new line.

## TBD

- Use `.eslintrc` config for code formatting, if one exists in the project.
